server {

    # Listen for HTTP requests on port 80
    listen 80;

    # Serve static frontend files
    location / {

        # Directory where index.html, style.css and script.js are stored
        root /usr/share/nginx/html;

        # Default file to load
        index index.html;

        # If the requested file doesn't exist,
        # return index.html instead
        try_files $uri $uri/ /index.html;
    }

    # Forward API requests to the backend container
    location /todos {

        # "backend" is the Docker Compose service name
        # Docker automatically resolves it.
        proxy_pass http://backend.todo-app.svc.cluster.local:3000;
    }
}