apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo
    component: backend
spec:
  type: ClusterIP
  selector:
    app: todo
    component: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000