apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo
    component: frontend

spec:
  type: ClusterIP

  selector:
    app: todo
    component: frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80